[package]
name = "file_upload_service"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-multipart = "0.4"
futures = "0.3"
sanitize-filename = "0.5"
tokio = { version = "1", features = ["full"] }
env_logger = "0.9"
log = "0.4"
